- name: javac
  weight: 20
  condition: 40
# depends-on is optional
# depends-on:
  context: Java source compilation
  configuration:
- name: junit
  weight: 80
  condition: 40
  context: Junit tests
  depends-on:
    - javac
  configuration:
    test_files:
      repository: this
      branch: main
      sha: latest
    timeout: 1m
